<?php
if ($_SERVER['REQUEST_METHOD']==='POST') {
    db()->prepare('INSERT INTO po_headers (po_number, po_date, po_type, vendor_name, supplier_code, company_code, purchasing_org, purchasing_group, currency, payment_terms, delivery_terms, contract_reference, pr_reference, validity_date, status, remarks, total_amount, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW())')
      ->execute([$_POST['po_number'],$_POST['po_date'],$_POST['po_type'],$_POST['vendor_name'],$_POST['supplier_code'],$_POST['company_code'],$_POST['purchasing_org'],$_POST['purchasing_group'],$_POST['currency'],$_POST['payment_terms'],$_POST['delivery_terms'],$_POST['contract_reference'],$_POST['pr_reference'],$_POST['validity_date'],$_POST['status'],$_POST['remarks'],$_POST['total_amount']]);
    log_audit('submit','po','PO saved/submitted');
}
$rows=db()->query('SELECT * FROM po_headers ORDER BY id DESC LIMIT 50')->fetchAll();
?>
<div class="card p-3"><h5>Create PO</h5><form method="post" class="row g-2"><div class="col-md-3"><input class="form-control" name="po_number" placeholder="PO Number" required></div><div class="col-md-2"><input type="date" class="form-control" name="po_date" required></div><div class="col-md-2"><select name="po_type" class="form-select"><option>Standard</option><option>Service</option></select></div><div class="col-md-3"><input class="form-control" name="vendor_name" placeholder="Vendor"></div><div class="col-md-2"><input class="form-control" name="supplier_code" placeholder="Supplier Code"></div><div class="col-md-2"><input class="form-control" name="company_code" placeholder="Company Code"></div><div class="col-md-2"><input class="form-control" name="purchasing_org" placeholder="Purchasing Org"></div><div class="col-md-2"><input class="form-control" name="purchasing_group" placeholder="Purchasing Group"></div><div class="col-md-2"><input class="form-control" name="currency" value="AED"></div><div class="col-md-2"><input class="form-control" name="payment_terms" placeholder="Payment Terms"></div><div class="col-md-2"><input class="form-control" name="delivery_terms" placeholder="Delivery Terms"></div><div class="col-md-2"><input class="form-control" name="contract_reference" placeholder="Contract Ref"></div><div class="col-md-2"><input class="form-control" name="pr_reference" placeholder="PR Ref"></div><div class="col-md-2"><input type="date" class="form-control" name="validity_date"></div><div class="col-md-2"><select class="form-select" name="status"><option>Draft</option><option>Submitted</option><option>Released</option></select></div><div class="col-md-2"><input class="form-control" name="total_amount" placeholder="Total AED"></div><div class="col-md-4"><input class="form-control" name="remarks" placeholder="Remarks"></div><div class="col-md-2"><button class="btn btn-warning">Save Draft / Submit PO</button></div></form><hr><table class="table table-sm"><tr><th>PO #</th><th>Date</th><th>Vendor</th><th>Total</th><th>Status</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['po_number'])?></td><td><?=e($r['po_date'])?></td><td><?=e($r['vendor_name'])?></td><td><?=number_format((float)$r['total_amount'],2)?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></table></div>
