<?php
if ($_SERVER['REQUEST_METHOD']==='POST') {
    db()->prepare('INSERT INTO pr_headers (pr_number, pr_date, pr_type, requestor, department, business_unit, currency, required_delivery_date, priority, status, justification, remarks, created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,NOW())')
      ->execute([$_POST['pr_number'],$_POST['pr_date'],$_POST['pr_type'],$_POST['requestor'],$_POST['department'],$_POST['business_unit'],$_POST['currency'],$_POST['required_delivery_date'],$_POST['priority'],$_POST['status'],$_POST['justification'],$_POST['remarks']]);
    log_audit('submit','pr','PR saved/submitted');
}
$rows=db()->query('SELECT * FROM pr_headers ORDER BY id DESC LIMIT 50')->fetchAll();
?>
<div class="card p-3"><h5>Create PR</h5><form method="post" class="row g-2"><div class="col-md-3"><input class="form-control" name="pr_number" placeholder="PR Number" required></div><div class="col-md-2"><input type="date" class="form-control" name="pr_date" required></div><div class="col-md-2"><select name="pr_type" class="form-select"><option>CAPEX</option><option>OPEX</option></select></div><div class="col-md-2"><input class="form-control" name="requestor" placeholder="Requestor"></div><div class="col-md-3"><input class="form-control" name="department" placeholder="Department"></div><div class="col-md-3"><input class="form-control" name="business_unit" placeholder="Business Unit"></div><div class="col-md-2"><input class="form-control" name="currency" value="AED"></div><div class="col-md-3"><input type="date" class="form-control" name="required_delivery_date"></div><div class="col-md-2"><select name="priority" class="form-select"><option>Low</option><option>Medium</option><option>High</option></select></div><div class="col-md-2"><select name="status" class="form-select"><option>Draft</option><option>Submitted</option></select></div><div class="col-md-6"><input class="form-control" name="justification" placeholder="Reference / Justification"></div><div class="col-md-6"><input class="form-control" name="remarks" placeholder="Remarks"></div><div class="col-md-3"><button class="btn btn-warning">Save Draft / Submit PR</button></div></form><hr><table class="table table-sm"><tr><th>PR #</th><th>Date</th><th>Type</th><th>Status</th></tr><?php foreach($rows as $r):?><tr><td><?=e($r['pr_number'])?></td><td><?=e($r['pr_date'])?></td><td><?=e($r['pr_type'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></table></div>
